= Spring Boot RestAPI Foundation

This is a project contains the following technologies:

* SpringBoot
* Spring RestAPI
* Spring OAuth2
* Spring DataJPA
* Swagger UI
* MySQL
* WAR and JAR Packaging 


== Installation and Getting Started

* Clone the Repository by using below command
[indent=0]
----
	git clone https://github.com/irfannasim/HIS-BE.git
----

* Import into Intellj Idea as maven project
* Dependencies will be start downloading
* Check the database credentials and DB name in applicatoin.properties file
* Execute the initial sql script from sql folder in your database which contains the OAuth2 configuration tables
* click on Run button to start 


== HOW to RUN / WHERE to START 

== GET Access Token Call

TIP: HTTP Request Type: `POST`

First of all in OAuth2 specification we need to get access_token to access resource (API). For getting access_token you have to follow the below and you can request from any HTTP client like `PostMan`:

* Call to below url
[indent=0]
----
	http://localhost:8080/his/oauth/token?username=superadmin&password=Password*1&grant_type=password
----

here in above url:

* meaning of `/his` is `context_path` configured in `applicaiton.properties` file
* meaning of `username` is username which is stored in DB
* meaning of `password` is password which is stored in DB

* The headers of this call should be 

[indent=0]
----
	content_type : application/json
	authorization: Base64 Encoded string of username:password
----

== Access to Any Resource (API) 

* Resource URL 

[indent=0]
----
	http://localhost:8080/his/user/get/1
----

TIP: HTTP Request Type: `GET`

here in above url:

* meaning of `/user` is path of the controller --> method (resource / API) which can be found in:

[indent=0]
----
	/src/main/java/com/sd/his/controller/UserAPI.java\getUserById();
----

* meaning of `get` url to get user
* meaning of `1` it is `id` of the user stored in DB

* The headers of this call should be 

[indent=0]
----
	content_type : application/json
	authorization: Bearer `access_token`
----

* access_token in above header mean, the access token string which is recieved in response of `http://localhost:8080/his/oauth/token?username=superadmin&password=Password*1&grant_type=password` API call.

Now, you can find the resource from controllers and made calls to other resource with belonging payloads.

If you need API documentation, please refere to below url of swagger documentation UI:

[indent=0]
----
	http://localhost:8080/swagger_ui.html
----
























